window.topics =
    "Tisíce vězňů na svobodě"
    "Konec krize?"
    "Bitva o Hrad"
    "Velká voda"
    "Konec Nečasovy vlády"
    "Rusnok & spol."
    "Buldozer Babiš"
    "Předčasně k urnám"
    "Jak sestrojit koalici"
    "ČNB torpéduje korunu"
    "ČEZká republika"
    "Impérium PPF"
    "Obchody roku"
    "Podezření, zločiny a tresty"
    "Odcházení"
    "Ženy u kormidla"
