window.topics =
    "Klaus propustil tisíce vězňů"
    "Konec krize?"
    "Prezidentské volby"
    "Pád vlády"
    "Předčasné volby"
    "Miloš Zeman"
    "Jiří Rusnok"
    "Andrej Babiš"
    "Petr Nečas"
    "ČEZ"
    "Obchody roku"
    "Krize"
    "Korupce"
    "Zahraničí"
    "Inovace"
